apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: http-route.yaml
  - target:
      group: kustomize.config.k8s.io
      version: v1beta1
      kind: Kustomization
    patch: |-
      - op: add
        path: /helmCharts/0/valuesInline
        value:
          gitea:
            config:
              server:
                DOMAIN: git.voltade.app
                ROOT_URL: https://git.voltade.app
              service:
                DISABLE_REGISTRATION: true
