apiVersion: v1
kind: Secret
metadata:
  name: repo-helm-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
stringData:
  type: helm
  name: helm-oci
  url: registry
  insecure: "true"
  enableOCI: "true"
