# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
configs:
  params:
    # https://github.com/argoproj/argo-cd/issues/2953#issuecomment-1565944622
    server.insecure: true
  cm:
    admin.enabled: true
    users.anonymous.enabled: false
    kustomize.buildOptions: "--enable-helm"
    resource.exclusions: |
      - apiGroups:
        - cilium.io
        kinds:
        - CiliumIdentity
        clusters:
        - "*"

server:
  ingress:
    enabled: false

repoServer:
  env:
    # https://github.com/argoproj/argo-cd/issues/13726#issuecomment-2733477259
    - name: SSL_CERT_DIR
      value: /mnt/ca-certificates
  volumeMounts:
    - name: voltade-os
      mountPath: /mnt/voltade-os.git
    - name: extra-ca
      mountPath: /mnt/ca-certificates
  volumes:
    - name: voltade-os
      hostPath:
        path: /mnt/voltade-os.git
        type: Directory
    - name: extra-ca
      configMap:
        name: argocd-tls-certs-cm
