# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false

additionalArguments:
  - "--entryPoints.postgres.address=:5432/tcp"

ports:
  web:
    expose:
      default: false
  websecure:
    expose:
      default: false
  postgres:
    port: 5432
    nodePort: 30432
    expose:
      default: true
    protocol: TCP

service:
  type: NodePort

gateway:
  enabled: false
