apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: hydra
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  cluster:
    name: cnpg-cluster
  name: hydra
  owner: hydra_admin
  ensure: present
