{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "runner.fullname" . }}
  labels:
    {{- include "runner.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httproute.gatewayName }}
      namespace: {{ .Values.httproute.gatewayNamespace }}
  hostnames:
    {{- range .Values.httproute.hostnames }}
    - "{{ . }}"
    {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "runner.fullname" . }}
          port: {{ .Values.service.port }}
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end }}
