apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/voltade/os.git
        revision: HEAD
        directories:
          - path: argocd/infra/*/overlays/prod
  template:
    metadata:
      name: "{{ index .path.segments 2 }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/voltade/os.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ index .path.segments 2 }}"
