apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitea
spec:
  parentRefs:
    - name: http
      namespace: gateway
  hostnames:
    - gitea.127-0-0-1.sslip.io
  rules:
    - backendRefs:
        - name: gitea-http
          port: 3000
      matches:
        - path:
            type: PathPrefix
            value: /
