# Default values for environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

id: orgId-envId
slug: org-env
organizationId: orgId
organizationSlug: orgSlug
organizationName: Org
environmentId: envId
environmentSlug: env
environmentName: Env
baseDomain: 127.0.0.1.nip.io
jwt:
  publicKey: ""
  anonKey: ""
  serviceKey: ""

nameOverride: ""
fullnameOverride: ""

runner:
  fullnameOverride: runner
  httproute:
    enabled: true
    gatewayName: cilium-gateway
    gatewayNamespace: gateway
    hostnames:
      - org-env.127.0.0.1.nip.io
  image:
    repository: registry.127.0.0.1.nip.io/runner
    pullPolicy: Always
    tag: latest
  environment:
    IS_PRODUCTION: "false"
    PLATFORM_URL: http://platform.platform.svc.cluster.local:5173
    RUNNER_SECRET_TOKEN:
      valueFrom:
        secretKeyRef:
          name: shared-secrets
          key: runnerSecretToken
    POSTGREST_URL: http://postgrest:3000
    SUPABASE_META_URL: http://supabase-meta:8080
    SUPABASE_STORAGE_URL: http://supabase-storage:8000
    SUPABASE_STUDIO_URL: http://supabase-studio:3000
    AWS_S3_ENDPOINT: http://minio.minio.svc.cluster.local:9000
    AWS_REGION: ap-southeast-1
    AWS_S3_BUCKET: voltade-os
    AWS_ACCESS_KEY_ID: username
    AWS_SECRET_ACCESS_KEY: password
    DB_USER_AUTHENTICATOR:
      valueFrom:
        secretKeyRef:
          name: cnpg-authenticator
          key: username
    DB_PASSWORD_AUTHENTICATOR:
      valueFrom:
        secretKeyRef:
          name: cnpg-authenticator
          key: password
    DB_HOST:
      valueFrom:
        secretKeyRef:
          name: cnpg-authenticator
          key: host
    DB_PORT:
      valueFrom:
        secretKeyRef:
          name: cnpg-authenticator
          key: port
    DB_NAME:
      valueFrom:
        secretKeyRef:
          name: cnpg-authenticator
          key: dbname

openfga:
  # https://github.com/openfga/helm-charts/blob/main/charts/openfga/values.yaml
  replicaCount: 1
  fullnameOverride: openfga
  datastore:
    engine: postgres
    existingSecret: cnpg-openfga-admin
    secretKeys:
      uriKey: uri
      usernameKey: username
      passwordKey: password
    applyMigrations: true
    waitForMigrations: true
    migrationType: initContainer

postgrest:
  enabled: true
  fullnameOverride: postgrest
  httproute:
    enabled: true
    gatewayName: cilium-gateway
    gatewayNamespace: gateway
    hostnames:
      - postgrest.org-env.127.0.0.1.nip.io
  image:
    # https://hub.docker.com/r/postgrest/postgrest/tags
    tag: v13.0.4
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  environment:
    PGRST_DB_URI: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL)
    DB_DRIVER: postgres
    DB_HOST: cnpg-cluster-rw
    DB_PORT: 5432
    DB_USER:
      valueFrom:
        secretKeyRef:
          name: cnpg-authenticator
          key: username
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: cnpg-authenticator
          key: password
    DB_NAME:
      valueFrom:
        secretKeyRef:
          name: cnpg-authenticator
          key: dbname
    DB_SSL: disable
    PGRST_DB_ANON_ROLE: anon
    # TODO: add storage schema
    PGRST_DB_SCHEMAS: public
    PGRST_OPENAPI_MODE: disabled

supabase-meta:
  enabled: true
  fullnameOverride: supabase-meta
  image:
    # https://github.com/supabase/postgres-meta/pkgs/container/postgres-meta
    tag: v0.91.5
  httproute:
    enabled: true
    gatewayName: cilium-gateway
    gatewayNamespace: gateway
    hostnames:
      - supabase-meta.org-env.127.0.0.1.nip.io
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  environment:
    DB_DRIVER: postgres
    PG_META_DB_HOST: cnpg-cluster-rw
    PG_META_DB_PORT: 5432
    PG_META_DB_USER:
      valueFrom:
        secretKeyRef:
          name: cnpg-service-role
          key: username
    PG_META_DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: cnpg-service-role
          key: password
    PG_META_DB_NAME:
      valueFrom:
        secretKeyRef:
          name: cnpg-service-role
          key: dbname
    PG_META_DB_SSL_MODE: disable
    PG_META_PORT: "8080"

supabase-storage:
  enabled: true
  fullnameOverride: supabase-storage
  image:
    # https://github.com/supabase/storage/pkgs/container/storage-api
    tag: v1.26.4
  httproute:
    enabled: true
    gatewayName: cilium-gateway
    gatewayNamespace: gateway
    hostnames:
      - supabase-storage.org-env.127.0.0.1.nip.io
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m
  environment:
    PGRST_JWT_SECRET: ""
    NODE_ENV: production
    DB_DRIVER: postgres
    DB_HOST: cnpg-cluster-rw
    DB_PORT: 5432
    DB_USER:
      valueFrom:
        secretKeyRef:
          name: cnpg-cluster-app
          key: username
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: cnpg-cluster-app
          key: password
    DB_NAME:
      valueFrom:
        secretKeyRef:
          name: cnpg-cluster-app
          key: dbname
    DB_SSL: disable
    DATABASE_URL:
      value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL)"
    PGOPTIONS: "-c search_path=storage,public"
    FILE_SIZE_LIMIT: 104857600
    STORAGE_BACKEND: file
    STORAGE_FILE_BACKEND_PATH: ./data
    STORAGE_FILE_ETAG_ALGORITHM: md5

supabase-studio:
  enabled: true
  fullnameOverride: supabase-studio
  image:
    # https://github.com/supabase/supabase/pkgs/container/studio
    tag: 2025.08.25-sha-72a94af
  httproute:
    enabled: true
    gatewayName: cilium-gateway
    gatewayNamespace: gateway
    hostnames:
      - supabase.org-env.127.0.0.1.nip.io
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1024Mi
      cpu: 1000m
  environment:
    STUDIO_PORT: 3000
    NEXT_PUBLIC_ENABLE_LOGS: "false"
    NEXT_PUBLIC_ENABLE_TELEMETRY: "false"
    NEXT_PUBLIC_IS_PLATFORM: "false"
    NODE_ENV: "production"
    STUDIO_PG_META_URL: http://supabase-meta:8080
    POSTGREST_URL: http://postgrest:3000
    SUPABASE_PUBLIC_URL: http://supabase.org-env.127.0.0.1.nip.io
    NEXT_PUBLIC_STUDIO_URL: http://supabase.org-env.127.0.0.1.nip.io
    SUPABASE_URL: http://supabase.org-env.127.0.0.1.nip.io
    SUPABASE_ANON_KEY: ""
    SUPABASE_SERVICE_KEY: ""
    DEFAULT_ORGANIZATION_NAME: Voltade OS
    DEFAULT_PROJECT_NAME: Org

drizzle-gateway:
  enabled: true
  fullnameOverride: drizzle-gateway
  image:
    # https://github.com/orgs/drizzle-team/packages/container/package/gateway
    tag: 1.0.2
  httproute:
    enabled: true
    gatewayName: cilium-gateway
    gatewayNamespace: gateway
    hostnames:
      - drizzle.org-env.127.0.0.1.nip.io
  databases:
    - secretName: cnpg-cluster-app
      dbname: app
      dialect: postgresql
      host: cnpg-cluster-rw
      port: 5432
