ipam:
  mode: kubernetes
kubeProxyReplacement: true
operator:
  replicas: 1
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true
  hostNetwork:
    enabled: true
envoy:
  enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
        # Add NET_BIND_SERVICE to the list (keep the others!)
        - NET_BIND_SERVICE
        - NET_ADMIN
        - SYS_ADMIN
