apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterissuer.yaml

helmCharts:
  - repo: https://charts.jetstack.io
    name: cert-manager
    # https://artifacthub.io/packages/helm/cert-manager/cert-manager
    version: 1.18.2
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
    valuesInline:
      crds:
        enabled: true
