apiVersion: v1
kind: Secret
metadata:
  name: repo-git
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
stringData:
  type: git
  name: repo-git
  url: ${repo_url}
