import { writeFile } from 'node:fs/promises';
import { $ } from 'bun';

import { processSqlFile } from './utils/processSqlFile.ts';

const output = await $`bun run drizzle-kit generate --custom`.text();
const filename = output.match(/\S*\/\d+_\w+\.sql/);

if (!filename) {
  throw new Error('No SQL file generated by drizzle-kit');
}

const currentSql = await processSqlFile('src/current.sql');
await writeFile(filename[0], currentSql, 'utf-8');
