apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: oci://registry.127.0.0.1.nip.io
    name: storage
    releaseName: storage
    namespace: platform
    valuesInline:
      enabled: true
      replicaCount: 1
      image:
        repository: supabase/storage-api
        pullPolicy: IfNotPresent
      service:
        type: ClusterIP
        port: 5000
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
      environment:
        NODE_ENV: "production"
        AUTH_JWT_SECRET:
          valueFrom:
            secretKeyRef:
              name: platform-envs
              key: jwt-secret
        DB_DRIVER: postgres
        DB_HOST: cnpg-cluster-rw
        DB_PORT: 5432
        DB_USER:
          valueFrom:
            secretKeyRef:
              name: platform-cluster-admin
              key: username
        DB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: platform-cluster-admin
              key: password
        DB_NAME: app
        DB_SSL: disable
        DATABASE_URL:
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL)"
        PGOPTIONS: "-c search_path=public"
        FILE_SIZE_LIMIT: 104857600
        STORAGE_BACKEND: file
        STORAGE_FILE_BACKEND_PATH: ./data
        STORAGE_FILE_ETAG_ALGORITHM: md5
