apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  cluster:
    name: cnpg-cluster
  name: platform
  owner: platform_admin
  ensure: present
  schemas:
    - name: extensions
      owner: platform_admin
    - name: openfga
      owner: openfga_admin
  extensions:
    - name: pgcrypto
      schema: extensions
    - name: plv8
      version: "3.2.3"
    - name: openfga
      schema: extensions
      version: "0.1"
