apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cluster-secret-store.yaml
  - ./cnpg-cluster.yaml
  - ./cnpg-route.yaml

helmCharts:
  - repo: oci://registry.127.0.0.1.nip.io
    name: platform
    version: 0.1.7
    releaseName: platform
    namespace: platform
