apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: oci://registry.127.0.0.1.nip.io
    name: platform
    version: 0.1.4
    releaseName: platform
    namespace: platform
