apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - smtp-route.yaml
  - httproute.yaml

helmCharts:
  - repo: https://charts.christianhuth.de
    name: maildev
    # https://artifacthub.io/packages/helm/christianhuth/maildev
    version: 1.3.4
    releaseName: maildev
    namespace: maildev
    valuesInline:
      maildev:
        config:
          smtp:
            incoming:
              username: username
              password: password
            outgoing:
              username: username
              password: password
