{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-envs
type: Opaque
data:
  jwt-secret: {{ .Values.secret.jwt.secret | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "gateway/tls-ca"
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "gateway/tls-certificate"
