{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: voltade-os-cluster-admin
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.secret.clusterAdmin.username | b64enc | quote }}
  password: {{ .Values.secret.clusterAdmin.password | b64enc | quote }}
{{- end }}
---
{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: voltade-os-envs
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled-namespaces: "*"
type: Opaque
data:
  jwt-secret: {{ .Values.secret.jwt.secret | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-ca
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "gateway/tls-ca"
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "gateway/tls-certificate"
