{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "voltade-os.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

{{- if .Values.rbac.create }}
{{- if .Values.rbac.rules.manageClusters }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-clusters
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
rules:
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters"]
    verbs: ["get", "watch", "delete", "create", "list", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-clusters
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "voltade-os.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "voltade-os.fullname" . }}-manage-clusters
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.rbac.rules.manageSecrets }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-secrets
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list", "create", "delete", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-secrets
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "voltade-os.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "voltade-os.fullname" . }}-manage-secrets
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.rbac.rules.managePods }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-pods
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["list", "get", "create", "delete", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-pods
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "voltade-os.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "voltade-os.fullname" . }}-manage-pods
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.rbac.rules.manageClusterRoleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-clusterrolebindings
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["list", "get", "create", "delete", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-clusterrolebindings
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "voltade-os.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "voltade-os.fullname" . }}-manage-clusterrolebindings
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.rbac.rules.manageServiceAccounts }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-service-accounts
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["list", "get", "create", "delete", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-service-accounts
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "voltade-os.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "voltade-os.fullname" . }}-manage-service-accounts
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.rbac.rules.devContainerAccess }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "voltade-os.fullname" . }}-dev-container-remote-access
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "pods/portforward"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "voltade-os.fullname" . }}-dev-container-remote-access
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "voltade-os.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "voltade-os.fullname" . }}-dev-container-remote-access
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.rbac.rules.manageIngresses }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-ingresses
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-ingresses
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "voltade-os.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "voltade-os.fullname" . }}-manage-ingresses
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.rbac.rules.manageNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-namespaces
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get", "create", "delete", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "voltade-os.fullname" . }}-manage-namespaces
  labels:
    {{- include "voltade-os.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "voltade-os.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "voltade-os.fullname" . }}-manage-namespaces
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
