apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-platform-migrator
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-64-length
  refreshPolicy: OnChange
  target:
    name: cnpg-platform-migrator
    template:
      # https://external-secrets.io/latest/guides/templating/#examples
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: platform_migrator
        # password: "{{ .password }}"
        password: password
