apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml

helmCharts:
  - repo: https://inbucket.github.io/inbucket-community
    name: inbucket
    # https://artifacthub.io/packages/helm/inbucket/inbucket
    version: 2.5.0
    releaseName: inbucket
    namespace: inbucket
    valuesInline: {}
