apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: worker
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  podTemplate:
    spec:
      # https://piraeus.io/docs/v2.9.0/how-to/talos/#configure-the-drbd-module-loader
      initContainers:
        - name: drbd-shutdown-guard
          $patch: delete
        - name: drbd-module-loader
          $patch: delete
      volumes:
        - name: run-systemd-system
          $patch: delete
        - name: run-drbd-shutdown-guard
          $patch: delete
        - name: systemd-bus-socket
          $patch: delete
        - name: lib-modules
          $patch: delete
        - name: usr-src
          $patch: delete
        - name: etc-lvm-backup
          hostPath:
            path: /var/etc/lvm/backup
            type: DirectoryOrCreate
        - name: etc-lvm-archive
          hostPath:
            path: /var/etc/lvm/archive
            type: DirectoryOrCreate
  storagePools:
    - name: worker-pool
      fileThinPool:
        directory: /var/lib/piraeus-datastore/worker-pool
