apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: oci://registry.127.0.0.1.nip.io
    name: supabase-meta
    releaseName: supabase-meta
    namespace: platform
    valuesInline:
      enabled: true
      replicaCount: 1
      image:
        repository: supabase/postgres-meta
        pullPolicy: IfNotPresent
      service:
        type: ClusterIP
        port: 8080
      resources:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 128Mi
          cpu: 50m
      environment:
        DB_DRIVER: postgres
        PG_META_DB_HOST: cnpg-cluster-rw
        PG_META_DB_PORT: 5432
        PG_META_DB_USER:
          valueFrom:
            secretKeyRef:
              name: cnpg-cluster-app
              key: username
        PG_META_DB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: cnpg-cluster-app
              key: password
        PG_META_DB_NAME: app
        PG_META_DB_SSL_MODE: disable
        PG_META_PORT: "8080"
