apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # https://github.com/cloudnative-pg/postgres-containers/pkgs/container/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-202509091311-minimal-trixie

  instances: 3

  # https://cloudnative-pg.io/documentation/current/scheduling/#isolating-postgresql-workloads
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
      - key: node-role.kubernetes.io/postgres
        operator: Exists
        effect: NoSchedule

  # https://cloudnative-pg.io/documentation/current/resource_management/
  resources:
    requests:
      memory: 1Gi
      cpu: "1"
    limits:
      memory: 1Gi
      cpu: "1"

  postgresql:
    parameters:
      shared_buffers: "256MB"

  # https://cloudnative-pg.io/documentation/current/storage/
  storage:
    storageClass: rawfile-retain
    size: 4Gi
  # https://cloudnative-pg.io/documentation/current/storage/#volume-for-wal
  walStorage:
    storageClass: rawfile-retain
    size: 1Gi

  # https://cloudnative-pg.io/documentation/current/recovery/#pitr-from-an-object-store
  # bootstrap:
  #   recovery:
  #     source: clusterBackup

  # https://cloudnative-pg.io/plugin-barman-cloud/docs/usage/#restoring-a-cluster
  externalClusters:
    - name: clusterBackup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: cnpg-object-store
          serverName: gitea-202509111622

  # https://cloudnative-pg.io/plugin-barman-cloud/docs/usage/#configuring-wal-archiving
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-object-store
        serverName: gitea-202509111622
