apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
spec:
  instances: 3

  # https://cloudnative-pg.io/documentation/current/scheduling/#isolating-postgresql-workloads
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
      - key: node-role.kubernetes.io/postgres
        operator: Exists
        effect: NoSchedule

  # https://cloudnative-pg.io/documentation/current/storage/
  storage:
    storageClass: rawfile-retain
    size: 4Gi
  # https://cloudnative-pg.io/documentation/current/storage/#volume-for-wal
  walStorage:
    storageClass: rawfile-retain
    size: 1Gi
