apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: http-route.yaml
  - target:
      group: kustomize.config.k8s.io
      version: v1beta1
      kind: Kustomization
    patch: |-
      helmCharts:
        - valuesInline:
            gitea:
              config:
                server:
                  DOMAIN: git.127.0.0.1.nip.io
                  ROOT_URL: http://git.127.0.0.1.nip.io
