apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # https://github.com/cloudnative-pg/plugin-barman-cloud/releases
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.6.0/manifest.yaml

helmCharts:
  - repo: https://cloudnative-pg.github.io/charts
    name: cloudnative-pg
    # https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
    version: 0.26.0
    releaseName: cloudnative-pg
    namespace: cnpg-system
    # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml
    valuesInline:
      replicaCount: 3
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname

patches:
  - target:
      kind: CustomResourceDefinition
      name: ".*"
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true

  # https://github.com/cloudnative-pg/plugin-barman-cloud/blob/v0.6.0/kubernetes/deployment.yaml
  - target:
      kind: Deployment
      name: barman-cloud
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node-role.kubernetes.io/control-plane: ""
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
      - op: add
        path: /spec/template/spec/affinity
        value:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - topologyKey: kubernetes.io/hostname
