apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # https://github.com/cloudnative-pg/plugin-barman-cloud/releases
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.5.0/manifest.yaml

helmCharts:
  - repo: https://cloudnative-pg.github.io/charts
    name: cloudnative-pg
    # https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
    version: 0.25.0
    releaseName: cloudnative-pg
    namespace: cnpg-system
    # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml
    valuesInline: {}

patches:
  - target:
      kind: CustomResourceDefinition
      name: ".*"
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true
