apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environment
  namespace: argocd
spec:
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Plugin/
  generators:
    - plugin:
        configMapRef:
          name: environment-generator
        requeueAfterSeconds: 15
  template:
    metadata:
      name: "org-{{ .variables.orgId }}-{{ .variables.environmentId }}"
      labels:
        orgId: "{{ .variables.orgId }}"
        isProduction: "{{ .variables.isProduction }}"
    spec:
      project: default
      source:
        repoURL: registry.127.0.0.1.nip.io
        chart: environment
        targetRevision: "{{ .variables.environmentChartVersion}}"
        helm:
          values: |
            {{ .values | toYaml }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
      destination:
        server: https://kubernetes.default.svc
        namespace: "org-{{ .variables.orgId }}-{{ .variables.environmentId }}"
