apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: oci://registry.127.0.0.1.nip.io
    name: supabase-studio
    releaseName: supabase-studio
    namespace: platform
    valuesInline:
      enabled: true
      global:
        enabled: false
      replicaCount: 1
      image:
        repository: supabase/studio
        pullPolicy: IfNotPresent
      service:
        type: ClusterIP
        port: 3000
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
      livenessProbe:
        httpGet:
          path: /api/platform/profile
          port: 3000
        initialDelaySeconds: 30
      environment:
        SUPABASE_PUBLIC_URL: http://supabase.127.0.0.1.nip.io
        NEXT_PUBLIC_STUDIO_URL: http://supabase.127.0.0.1.nip.io
        SUPABASE_URL: http://platform-kong:80
        STUDIO_PG_META_URL: http://platform-meta:8080
        POSTGREST_URL: http://platform-rest:3000
        AUTH_JWT_SECRET:
          valueFrom:
            secretKeyRef:
              name: platform-envs
              key: jwt-secret
        STUDIO_PORT: 3000
        NEXT_PUBLIC_ENABLE_LOGS: "false"
        NEXT_PUBLIC_ENABLE_TELEMETRY: "false"
        NODE_ENV: "production"
