apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-generator.yaml

helmCharts:
  - repo: https://charts.external-secrets.io
    name: external-secrets
    # https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
    version: 0.19.2
    releaseName: external-secrets
    namespace: external-secrets

patches:
  - target:
      kind: CustomResourceDefinition
      name: ".*"
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true
