apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: oci://registry.127.0.0.1.nip.io
    name: postgrest
    releaseName: postgrest
    namespace: platform
    valuesInline:
      enabled: true
      replicaCount: 1
      image:
        repository: postgrest/postgrest
        pullPolicy: IfNotPresent
      service:
        type: ClusterIP
        port: 3000
      resources:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 128Mi
          cpu: 50m
      environment:
        PGRST_DB_URI: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL)
        DB_DRIVER: postgres
        DB_HOST: cnpg-cluster-rw
        DB_PORT: 5432
        DB_USER:
          valueFrom:
            secretKeyRef:
              name: cnpg-platform-admin
              key: username
        DB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: cnpg-platform-admin
              key: password
        DB_NAME: platform
        DB_SSL: disable
        PGRST_APP_SETTINGS_JWT_EXP: 3600
        PGRST_DB_ANON_ROLE: anon
        PGRST_DB_SCHEMAS: public
        PGRST_OPENAPI_MODE: disabled
        PGRST_JWT_SECRET:
          valueFrom:
            secretKeyRef:
              name: platform-envs
              key: jwt-secret
        PGRST_APP_SETTINGS_JWT_SECRET:
          valueFrom:
            secretKeyRef:
              name: platform-envs
              key: jwt-secret
