apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://openebs.github.io/rawfile-localpv
    name: rawfile-localpv
    # https://artifacthub.io/packages/helm/rawfile/rawfile-localpv
    version: 0.11.0
    releaseName: rawfile-localpv
    namespace: openebs
    # https://github.com/openebs/rawfile-localpv/blob/develop/deploy/helm/rawfile-localpv/values.yaml
    valuesInline:
      controller:
        # From the helm chart default values, the controller StatefulSet's tolerations are using the deprecated key "node-role.kubernetes.io/master":
        # https://github.com/openebs/rawfile-localpv/blob/v0.11.0/deploy/helm/rawfile-localpv/values.yaml#L68
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 150Mi

      node:
        tolerations:
          - key: node-role.kubernetes.io/postgres
            operator: Exists
            effect: NoSchedule
      storageClass:
        name: rawfile-localpv
        defaultClass: false
        fsType: xfs

patches:
  # From the helm chart template, the controller StatefulSet doesn't support nodeSelector:
  # https://github.com/openebs/rawfile-localpv/blob/v0.11.0/deploy/helm/rawfile-localpv/templates/controller/statefulset.yaml
  - target:
      kind: StatefulSet
      name: rawfile-localpv-controller
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          node-role.kubernetes.io/control-plane: ""
