apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rawfile-localpv-retain
provisioner: rawfile.csi.openebs.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: xfs
  thinProvision: "false"
  formatOptions: ""
