apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-kratos-admin
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-64-length
  refreshPolicy: OnChange
  target:
    name: cnpg-kratos-admin
    template:
      # https://external-secrets.io/latest/guides/templating/#examples
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: kratos_admin
        password: "{{ .password }}"
