apiVersion: v1
kind: Secret
metadata:
  name: tls-ca
  annotations:
    argocd.argoproj.io/ignore-resource-updates: "true"
    reflector.v1.k8s.emberstack.com/reflects: "gateway/tls-ca"

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate
  annotations:
    argocd.argoproj.io/ignore-resource-updates: "true"
    reflector.v1.k8s.emberstack.com/reflects: "gateway/tls-certificate"
