/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MainProfileRouteImport } from './routes/_main.profile'
import { Route as MainApplicationsRouteImport } from './routes/_main.applications'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthSigninRouteImport } from './routes/_auth.signin'
import { Route as MainTeamIndexRouteImport } from './routes/_main.team.index'
import { Route as MainProfileIndexRouteImport } from './routes/_main.profile.index'
import { Route as MainEnvironmentsIndexRouteImport } from './routes/_main.environments.index'
import { Route as MainEnvironmentsEnvironmentSlugRouteImport } from './routes/_main.environments.$environmentSlug'
import { Route as MainAcceptInvitationInvitationIdRouteImport } from './routes/_main.accept-invitation.$invitationId'
import { Route as AuthOauthConsentRouteImport } from './routes/_auth.oauth.consent'
import { Route as MainEnvironmentsEnvironmentSlugIndexRouteImport } from './routes/_main.environments.$environmentSlug.index'
import { Route as MainEnvironmentsEnvironmentSlugEnvironment_variablesRouteImport } from './routes/_main.environments.$environmentSlug.environment_variables'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainApplicationsRoute = MainApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => MainRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const MainTeamIndexRoute = MainTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileIndexRoute = MainProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainProfileRoute,
} as any)
const MainEnvironmentsIndexRoute = MainEnvironmentsIndexRouteImport.update({
  id: '/environments/',
  path: '/environments/',
  getParentRoute: () => MainRoute,
} as any)
const MainEnvironmentsEnvironmentSlugRoute =
  MainEnvironmentsEnvironmentSlugRouteImport.update({
    id: '/environments/$environmentSlug',
    path: '/environments/$environmentSlug',
    getParentRoute: () => MainRoute,
  } as any)
const MainAcceptInvitationInvitationIdRoute =
  MainAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => MainRoute,
  } as any)
const AuthOauthConsentRoute = AuthOauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => AuthRoute,
} as any)
const MainEnvironmentsEnvironmentSlugIndexRoute =
  MainEnvironmentsEnvironmentSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainEnvironmentsEnvironmentSlugRoute,
  } as any)
const MainEnvironmentsEnvironmentSlugEnvironment_variablesRoute =
  MainEnvironmentsEnvironmentSlugEnvironment_variablesRouteImport.update({
    id: '/environment_variables',
    path: '/environment_variables',
    getParentRoute: () => MainEnvironmentsEnvironmentSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/applications': typeof MainApplicationsRoute
  '/profile': typeof MainProfileRouteWithChildren
  '/': typeof MainIndexRoute
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/accept-invitation/$invitationId': typeof MainAcceptInvitationInvitationIdRoute
  '/environments/$environmentSlug': typeof MainEnvironmentsEnvironmentSlugRouteWithChildren
  '/environments': typeof MainEnvironmentsIndexRoute
  '/profile/': typeof MainProfileIndexRoute
  '/team': typeof MainTeamIndexRoute
  '/environments/$environmentSlug/environment_variables': typeof MainEnvironmentsEnvironmentSlugEnvironment_variablesRoute
  '/environments/$environmentSlug/': typeof MainEnvironmentsEnvironmentSlugIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/applications': typeof MainApplicationsRoute
  '/': typeof MainIndexRoute
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/accept-invitation/$invitationId': typeof MainAcceptInvitationInvitationIdRoute
  '/environments': typeof MainEnvironmentsIndexRoute
  '/profile': typeof MainProfileIndexRoute
  '/team': typeof MainTeamIndexRoute
  '/environments/$environmentSlug/environment_variables': typeof MainEnvironmentsEnvironmentSlugEnvironment_variablesRoute
  '/environments/$environmentSlug': typeof MainEnvironmentsEnvironmentSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_main/applications': typeof MainApplicationsRoute
  '/_main/profile': typeof MainProfileRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_auth/oauth/consent': typeof AuthOauthConsentRoute
  '/_main/accept-invitation/$invitationId': typeof MainAcceptInvitationInvitationIdRoute
  '/_main/environments/$environmentSlug': typeof MainEnvironmentsEnvironmentSlugRouteWithChildren
  '/_main/environments/': typeof MainEnvironmentsIndexRoute
  '/_main/profile/': typeof MainProfileIndexRoute
  '/_main/team/': typeof MainTeamIndexRoute
  '/_main/environments/$environmentSlug/environment_variables': typeof MainEnvironmentsEnvironmentSlugEnvironment_variablesRoute
  '/_main/environments/$environmentSlug/': typeof MainEnvironmentsEnvironmentSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/signup'
    | '/applications'
    | '/profile'
    | '/'
    | '/oauth/consent'
    | '/accept-invitation/$invitationId'
    | '/environments/$environmentSlug'
    | '/environments'
    | '/profile/'
    | '/team'
    | '/environments/$environmentSlug/environment_variables'
    | '/environments/$environmentSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signup'
    | '/applications'
    | '/'
    | '/oauth/consent'
    | '/accept-invitation/$invitationId'
    | '/environments'
    | '/profile'
    | '/team'
    | '/environments/$environmentSlug/environment_variables'
    | '/environments/$environmentSlug'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_main/applications'
    | '/_main/profile'
    | '/_main/'
    | '/_auth/oauth/consent'
    | '/_main/accept-invitation/$invitationId'
    | '/_main/environments/$environmentSlug'
    | '/_main/environments/'
    | '/_main/profile/'
    | '/_main/team/'
    | '/_main/environments/$environmentSlug/environment_variables'
    | '/_main/environments/$environmentSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/applications': {
      id: '/_main/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof MainApplicationsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/team/': {
      id: '/_main/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof MainTeamIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile/': {
      id: '/_main/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof MainProfileIndexRouteImport
      parentRoute: typeof MainProfileRoute
    }
    '/_main/environments/': {
      id: '/_main/environments/'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof MainEnvironmentsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/environments/$environmentSlug': {
      id: '/_main/environments/$environmentSlug'
      path: '/environments/$environmentSlug'
      fullPath: '/environments/$environmentSlug'
      preLoaderRoute: typeof MainEnvironmentsEnvironmentSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/accept-invitation/$invitationId': {
      id: '/_main/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof MainAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/oauth/consent': {
      id: '/_auth/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof AuthOauthConsentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/environments/$environmentSlug/': {
      id: '/_main/environments/$environmentSlug/'
      path: '/'
      fullPath: '/environments/$environmentSlug/'
      preLoaderRoute: typeof MainEnvironmentsEnvironmentSlugIndexRouteImport
      parentRoute: typeof MainEnvironmentsEnvironmentSlugRoute
    }
    '/_main/environments/$environmentSlug/environment_variables': {
      id: '/_main/environments/$environmentSlug/environment_variables'
      path: '/environment_variables'
      fullPath: '/environments/$environmentSlug/environment_variables'
      preLoaderRoute: typeof MainEnvironmentsEnvironmentSlugEnvironment_variablesRouteImport
      parentRoute: typeof MainEnvironmentsEnvironmentSlugRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthOauthConsentRoute: typeof AuthOauthConsentRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthOauthConsentRoute: AuthOauthConsentRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainProfileRouteChildren {
  MainProfileIndexRoute: typeof MainProfileIndexRoute
}

const MainProfileRouteChildren: MainProfileRouteChildren = {
  MainProfileIndexRoute: MainProfileIndexRoute,
}

const MainProfileRouteWithChildren = MainProfileRoute._addFileChildren(
  MainProfileRouteChildren,
)

interface MainEnvironmentsEnvironmentSlugRouteChildren {
  MainEnvironmentsEnvironmentSlugEnvironment_variablesRoute: typeof MainEnvironmentsEnvironmentSlugEnvironment_variablesRoute
  MainEnvironmentsEnvironmentSlugIndexRoute: typeof MainEnvironmentsEnvironmentSlugIndexRoute
}

const MainEnvironmentsEnvironmentSlugRouteChildren: MainEnvironmentsEnvironmentSlugRouteChildren =
  {
    MainEnvironmentsEnvironmentSlugEnvironment_variablesRoute:
      MainEnvironmentsEnvironmentSlugEnvironment_variablesRoute,
    MainEnvironmentsEnvironmentSlugIndexRoute:
      MainEnvironmentsEnvironmentSlugIndexRoute,
  }

const MainEnvironmentsEnvironmentSlugRouteWithChildren =
  MainEnvironmentsEnvironmentSlugRoute._addFileChildren(
    MainEnvironmentsEnvironmentSlugRouteChildren,
  )

interface MainRouteChildren {
  MainApplicationsRoute: typeof MainApplicationsRoute
  MainProfileRoute: typeof MainProfileRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
  MainAcceptInvitationInvitationIdRoute: typeof MainAcceptInvitationInvitationIdRoute
  MainEnvironmentsEnvironmentSlugRoute: typeof MainEnvironmentsEnvironmentSlugRouteWithChildren
  MainEnvironmentsIndexRoute: typeof MainEnvironmentsIndexRoute
  MainTeamIndexRoute: typeof MainTeamIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainApplicationsRoute: MainApplicationsRoute,
  MainProfileRoute: MainProfileRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
  MainAcceptInvitationInvitationIdRoute: MainAcceptInvitationInvitationIdRoute,
  MainEnvironmentsEnvironmentSlugRoute:
    MainEnvironmentsEnvironmentSlugRouteWithChildren,
  MainEnvironmentsIndexRoute: MainEnvironmentsIndexRoute,
  MainTeamIndexRoute: MainTeamIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
