apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: openfga
  labels: {{- include "environment.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  cluster:
    name: cnpg-cluster
  name: openfga
  owner: openfga_admin
  ensure: present
