apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: cnpg-cluster-rw
  labels:
    {{- include "environment.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`{{ include "environment.fullname" . }}.{{ .Values.domain }}`)
      services:
        - name: cnpg-cluster-rw
          port: 5432
  tls:
    secretName: tls-certificate
    options:
      name: no-alpn

---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: no-alpn
spec:
  alpnProtocols: []
