apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  labels:
    {{- include "environment.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  # https://github.com/voltade/voltade-os/pkgs/container/postgres
  imageName: ghcr.io/voltade/postgres:17.5-20250717-a2c5abf
  instances: 1
  certificates:
    serverCASecret: cnpg-tls
    serverTLSSecret: cnpg-tls
  storage:
    size: 4Gi
  enableSuperuserAccess: true
  managed:
    roles:
      - name: authenticated
        inherit: false

      - name: service_role
        bypassrls: true

      - name: anon
        inherit: false
