apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  labels: {{- include "environment.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  # https://github.com/voltade/voltade-os/pkgs/container/postgres
  imageName: ghcr.io/voltade/postgres:17.5-20250717-a2c5abf
  instances: 1
  certificates:
    serverCASecret: cnpg-tls
    serverTLSSecret: cnpg-tls
  storage:
    size: 4Gi
  postgresql:
    parameters:
      pgsodium.enable_event_trigger: "off"
      pgsodium.getkey_script: /usr/share/postgresql/17/extension/pgsodium_getkey
    shared_preload_libraries:
      - supabase_vault
  managed:
    roles:
      - name: app
        login: true
        superuser: true
        
      - name: authenticator
        login: true
        inherit: false
        inRoles:
          - authenticated
        passwordSecret:
          name: cnpg-authenticator

      - name: authenticated
        inherit: false
      
      - name: anon
        inherit: false

      - name: service_role
        bypassrls: true

  bootstrap:
    initdb:
      database: app
      owner: app
      dataChecksums: true
      postInitApplicationSQL:
        - create schema if not exists extensions;
        - create extension supabase_vault cascade;
        - grant usage on schema vault to app;
        - grant execute on all functions in schema vault to app;
        - grant select on all tables in schema vault to app;
        - grant references on all tables in schema vault to app;
