apiVersion: v1
kind: Secret
metadata:
  name: tls-ca
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "gateway/tls-ca"

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "gateway/tls-certificate"
