services:
  postgres:
    image: ghcr.io/voltade/cnpg-supabase:17.5-system-1
    restart: unless-stopped
    env_file: ../../.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: {}
