{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "drizzle-gateway.fullname" . }}-secret-reader
  labels:
    {{- include "drizzle-gateway.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "drizzle-gateway.fullname" . }}-secret-reader
  labels:
    {{- include "drizzle-gateway.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
subjects:
- kind: ServiceAccount
  name: {{ include "drizzle-gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "drizzle-gateway.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
