apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "drizzle-gateway.fullname" . }}-store
  labels:
    {{- include "drizzle-gateway.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  data:
    {{- range $index, $db := .Values.databases }}
    - secretKey: username_{{ $index }}
      remoteRef:
        key: {{ $db.secretName }}
        property: username
    - secretKey: password_{{ $index }}
      remoteRef:
        key: {{ $db.secretName }}
        property: password
    {{- end }}
  secretStoreRef:
    name: {{ include "drizzle-gateway.fullname" . }}-local
    kind: SecretStore
  refreshPolicy: OnChange
  target:
    name: {{ include "drizzle-gateway.fullname" . }}-store
    template:
      engineVersion: v2
      type: Opaque
      data:
        store.json: |
          {
            "id": "{{ .Release.Namespace }}",
            "name": "{{ .Release.Namespace }}",
            "slots": [
              {{- range $index, $db := .Values.databases }}
              {{- if $index }},{{ end }}
              [
                "{{ $db.dbname | default $.Release.Namespace }}",
                {
                  "id": "{{ $db.dbname | default $.Release.Namespace }}",
                  "name": "{{ $db.dbname | default $.Release.Namespace }}",
                  "dialect": "{{ $db.dialect | default "postgresql" }}",
                  "credentials": {
                    "url": "{{ $db.dialect | default "postgresql" }}://{{ `{{ .username_` }}{{ $index }}{{ ` }}` }}:{{ `{{ .password_` }}{{ $index }}{{ ` }}` }}@{{ $db.host | default "cnpg-cluster-rw" }}:{{ $db.port | default 5432 }}/{{ $db.dbname | default "app" }}"
                  }
                }
              ]
              {{- end }}
            ]
          }
