apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "drizzle-gateway.fullname" . }}-local
  labels:
    {{- include "drizzle-gateway.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    kubernetes:
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ include "drizzle-gateway.serviceAccountName" . }}
      remoteNamespace: {{ .Release.Namespace }}
