apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: kratos
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  cluster:
    name: cnpg-cluster
  name: kratos
  owner: kratos_admin
  ensure: present
