apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cnpg-database.yaml
  - httproute-public.yaml
  - httproute-admin.yaml
  - secret-dsn.yaml

helmCharts:
  - repo: https://k8s.ory.sh/helm/charts
    name: kratos
    # https://artifacthub.io/packages/helm/ory/kratos
    version: 0.56.0
    releaseName: kratos
    namespace: platform
    # https://artifacthub.io/packages/helm/ory/kratos?modal=values
    valuesInline:
      image:
        tag: v1.3.1-distroless

      # https://k8s.ory.sh/helm/kratos.html#installation
      kratos:
        development: true

        # https://www.ory.sh/docs/kratos/quickstart#quickstart-configuration
        # https://www.ory.sh/docs/kratos/reference/configuration
        config:
          dev: true

          serve:
            public:
              base_url: http://kratos.127.0.0.1.nip.io

              # https://www.ory.sh/docs/kratos/guides/setting-up-cors
              cors:
                enabled: true
                allowed_origins:
                  - http://127.0.0.1.nip.io
                  - http://*.127.0.0.1.nip.io
                allowed_methods:
                  - POST
                  - GET
                  - PUT
                  - PATCH
                  - DELETE
                allowed_headers:
                  - Authorization
                  - Cookie
                  - Content-Type
                exposed_headers:
                  - Content-Type
                  - Set-Cookie

            admin:
              base_url: http://kratos-admin

          session:
            whoami:
              required_aal: aal1

          selfservice:
            default_browser_return_url: http://127.0.0.1.nip.io/settings
            allowed_return_urls:
              - http://127.0.0.1.nip.io

            methods:
              password:
                enabled: false
              passkey:
                enabled: false
              code:
                passwordless_enabled: true
              # https://www.ory.sh/docs/kratos/passwordless/passkeys#passkeys-with-the-dedicated-passkey-strategy
              webauthn:
                enabled: true
                config:
                  passwordless: false
                  rp:
                    display_name: Voltade
                    id: voltade.com
                    origin: http://127.0.1.nip.io
              totp:
                config:
                  issuer: Kratos
                enabled: true
              lookup_secret:
                enabled: true
              link:
                enabled: true

            flows:
              error:
                ui_url: http://127.0.0.1.nip.io/error
              settings:
                ui_url: http://127.0.0.1.nip.io/settings
                privileged_session_max_age: 15m
                # https://www.ory.sh/docs/kratos/self-hosted/mfa#enforce-mfa
                required_aal: highest_available
              recovery:
                enabled: true
                ui_url: http://127.0.0.1.nip.io/recovery
                use: code
              verification:
                enabled: true
                ui_url: http://127.0.0.1.nip.io/verification
                use: code
                after:
                  default_browser_return_url: http://127.0.0.1.nip.io/settings
              login:
                ui_url: http://127.0.0.1.nip.io/login
                lifespan: 1h
                style: unified
              registration:
                lifespan: 1h
                ui_url: http://127.0.0.1.nip.io/registration

          identity:
            default_schema_id: default
            schemas:
              - id: default
                url: file:///etc/config/identity.default.schema.json
          courier:
            # https://www.ory.sh/docs/kratos/emails-sms/sending-emails-smtp#smtp-security-mechanisms
            smtp:
              connection_uri: smtp://inbucket.inbucket.svc.cluster.local:2500/?disable_starttls=true
            sms:
              enabled: true
              from: "Voltade"
              request_config:
                url: https://api.twillio.com/sms/send
                method: ""
                headers: {}
                body: file:///path/to/body.jsonnet
                auth:
                  type: api_key
                  config:
                    name: ""
                    value: ""
                    in: header

        automigration:
          enabled: true
          type: initContainer

        identitySchemas:
          "identity.default.schema.json": |
            {
              "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
              "$schema": "http://json-schema.org/draft-07/schema#",
              "title": "Person",
              "type": "object",
              "properties": {
                "traits": {
                  "type": "object",
                  "properties": {
                    "email": {
                      "type": "string",
                      "format": "email",
                      "title": "E-Mail",
                      "ory.sh/kratos": {
                        "credentials": {
                          "code": {
                            "identifier": true,
                            "via": "email"
                          }
                        },
                        "recovery": {
                          "via": "email"
                        },
                        "verification": {
                          "via": "email"
                        }
                      }
                    },
                    "phone_number": {
                      "type": "string",
                      "format": "tel",
                      "title": "Your phone number",
                      "ory.sh/kratos": {
                        "credentials": {
                          "code": {
                            "identifier": true,
                            "via": "sms"
                          }
                        }
                      }
                    }
                  },
                  "anyOf": [
                    { "required": ["email"] },
                    { "required": ["phone_number"] }
                  ],
                  "additionalProperties": false
                }
              }
            }

      # https://k8s.ory.sh/helm/kratos.html#set-up-dsn-variable-on-runtime
      deployment:
        extraEnv:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: kratos-dsn
                key: dsn
      statefulSet:
        extraEnv:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: kratos-dsn
                key: dsn
      job:
        extraEnv:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: kratos-dsn
                key: dsn
      cronjob:
        cleanup:
          extraEnv:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: kratos-dsn
                  key: dsn
