apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: verdaccio
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway
  hostnames:
    - npm.127.0.0.1.nip.io
  rules:
    - backendRefs:
        - name: verdaccio
          port: 4873
      matches:
        - path:
            type: PathPrefix
            value: /
