apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml

helmCharts:
  - repo: https://charts.verdaccio.org
    name: verdaccio
    # https://github.com/verdaccio/charts/releases
    version: 4.26.1
    releaseName: verdaccio
    namespace: verdaccio
    # https://github.com/verdaccio/charts/blob/master/charts/verdaccio/values.yaml
    valuesInline:
      configMap: |
        storage: /verdaccio/storage/data
        uplinks:
          npmjs:
            url: https://registry.npmjs.org/
            agent_options:
              keepAlive: true
              maxSockets: 40
              maxFreeSockets: 10
        packages:
          '@voltade/*':
            access: $all
            publish: $all
            proxy: npmjs
