/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductTemplatesRouteImport } from './routes/product-templates'
import { Route as IndexRouteImport } from './routes/index'

const ProductTemplatesRoute = ProductTemplatesRouteImport.update({
  id: '/product-templates',
  path: '/product-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product-templates': typeof ProductTemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product-templates': typeof ProductTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product-templates': typeof ProductTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/product-templates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/product-templates'
  id: '__root__' | '/' | '/product-templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductTemplatesRoute: typeof ProductTemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/product-templates': {
      id: '/product-templates'
      path: '/product-templates'
      fullPath: '/product-templates'
      preLoaderRoute: typeof ProductTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductTemplatesRoute: ProductTemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
